name: Deploy AWS resource using AWS S3 Backend Configuration

on:
  pull_request:
    branches:
      - main  # Adjust the branch name as needed
  workflow_dispatch:


jobs:
  configure-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            "us-east-1"  # Change to your AWS region

    - name: Configure Backend with AWS S3
      run: |
        # Replace these values with your AWS S3 bucket and key
        S3_BUCKET_NAME="terraform-backend-yv"

        aws configure set aws-access-key-id $AWS_ACCESS_KEY_ID
        aws configure set aws-secret-access-key $AWS_SECRET_ACCESS_KEY
        aws configure set region us-east-1  # Change this to your desired AWS region
        aws configure set preview.cloudfront true

        # Initialize Terraform with the AWS S3 backend configuration
        terraform init -backend-config="bucket=$S3_BUCKET_NAME"
      
        terraform validate
      working-directory: aws-infrastructure

    - name: Plan Terraform Changes
      run: terraform plan -out=tfplan
      working-directory: aws-infrastructure

    - name: Apply Terraform Changes
      run: |
        terraform apply -auto-approve "tfplan"
      working-directory: aws-infrastructure