name: Deploy AWS Infrastructure using single workflow

on:
  push:
    branches:
      - main  # Adjust to your repository's default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.2  # Replace with your desired Terraform version

    - name: Initialize Terraform
      run: terraform init
      working-directory: aws-infrastructure  # Adjust to your Terraform code location

    - name: Plan Terraform Changes
      run: terraform plan -out=tfplan
      working-directory: aws-infrastructure

    # - name: Apply Terraform Changes
    #   run: terraform apply -input=false tfplan
    #   working-directory: aws-infrastructure
    #   env:
    #     TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     TF_VAR_aws_region: us-east-1  # Adjust to your desired AWS region
    #   # Be sure to configure your GitHub repository secrets for AWS access keys

    # - name: Clean Up Terraform Files
    #   run: rm -f tfplan
    #   working-directory: path/to/terraform/code

